"""initial schema

Revision ID: edc255dd2dc8
Revises:
Create Date: 2026-09-12 12:55:04.457965
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'edc255dd2dc8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_principal_id', sa.String(), nullable=True),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_org_id'), ['org_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('principal_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('revoked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_org_id'), ['org_id'], unique=False)

    op.create_table('approvals',
    sa.Column('approval_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('intent_id', sa.String(), nullable=True),
    sa.Column('action_digest', sa.String(), nullable=True),
    sa.Column('action_summary_json', sa.String(), nullable=True),
    sa.Column('reasons_json', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('granted_by', sa.String(), nullable=True),
    sa.Column('requested_at', sa.String(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('approval_id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_action_digest'), ['action_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_session_id'), ['session_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('rowid_seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rowid_seq')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_org_seq', ['org_id', 'seq'], unique=True)

    op.create_table('capabilities',
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('intent_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scopes_json', sa.String(), nullable=True),
    sa.Column('budget_json', sa.String(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('revoked_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('capability_id')
    )
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capabilities_org_id'), ['org_id'], unique=False)

    op.create_table('decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('action_digest', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('intent_id', sa.String(), nullable=True),
    sa.Column('capability_id', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reasons_json', sa.String(), nullable=True),
    sa.Column('checks_json', sa.String(), nullable=True),
    sa.Column('risk_json', sa.String(), nullable=True),
    sa.Column('versions_json', sa.String(), nullable=True),
    sa.Column('approval_id', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('decision_id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_action_digest'), ['action_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_session_id'), ['session_id'], unique=False)

    op.create_table('executions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('action_digest', sa.String(), nullable=True),
    sa.Column('summary_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('decision_id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executions_action_digest'), ['action_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_session_id'), ['session_id'], unique=False)

    op.create_table('intents',
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('principal_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('constraints_json', sa.String(), nullable=True),
    sa.Column('allowed_operations_json', sa.String(), nullable=True),
    sa.Column('ambiguities_json', sa.String(), nullable=True),
    sa.Column('compiled_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('intent_id')
    )
    with op.batch_alter_table('intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intents_org_id'), ['org_id'], unique=False)

    op.create_table('organizations',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('policy_rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('layer', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('effect', sa.String(), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('max_amount', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rules_org_id'), ['org_id'], unique=False)

    op.create_table('principals',
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('principal_id')
    )
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principals_org_id'), ['org_id'], unique=False)

    op.create_table('session_observations',
    sa.Column('rowid_seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('obs_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rowid_seq')
    )
    with op.batch_alter_table('session_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_observations_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_observations_session_id'), ['session_id'], unique=False)

    op.create_table('sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('intent_id', sa.String(), nullable=True),
    sa.Column('capability_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('degraded', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_org_id'), ['org_id'], unique=False)

    op.create_table('trajectory_steps',
    sa.Column('rowid_seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('side_effect_class', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reasons_json', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('taint', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rowid_seq')
    )
    with op.batch_alter_table('trajectory_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trajectory_steps_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trajectory_steps_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trajectory_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trajectory_steps_session_id'))
        batch_op.drop_index(batch_op.f('ix_trajectory_steps_org_id'))

    op.drop_table('trajectory_steps')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_org_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('session_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_observations_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_observations_org_id'))

    op.drop_table('session_observations')
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principals_org_id'))

    op.drop_table('principals')
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_rules_org_id'))

    op.drop_table('policy_rules')
    op.drop_table('organizations')
    with op.batch_alter_table('intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intents_org_id'))

    op.drop_table('intents')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_session_id'))
        batch_op.drop_index(batch_op.f('ix_executions_org_id'))
        batch_op.drop_index(batch_op.f('ix_executions_action_digest'))

    op.drop_table('executions')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_session_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_org_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_action_digest'))

    op.drop_table('decisions')
    with op.batch_alter_table('capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capabilities_org_id'))

    op.drop_table('capabilities')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_seq')

    op.drop_table('audit_events')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_session_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_org_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_action_digest'))

    op.drop_table('approvals')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_org_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_org_id'))

    op.drop_table('agents')
    # ### end Alembic commands ###
